export type BrandColorGameFlag = {
  id: string;
  name: string;
  targetHex: string;
  answerName: string;
  flagSrc: string;
  missingFlagSrc: string;
  difficulty: 1 | 2 | 3;
  source: string;
};

const FLAG_SOURCE =
  "https://github.com/hampusborgos/country-flags/tree/main/svg";

export const BRAND_COLOR_GAME_FLAGS = [
  {
    id: "united-states",
    name: "United States",
    targetHex: "#3C3B6E",
    answerName: "United States flag blue",
    flagSrc: "/lab/brand-color-game/flags/united-states.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/united-states-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/us.svg`,
  },
  {
    id: "france",
    name: "France",
    targetHex: "#051440",
    answerName: "France flag blue",
    flagSrc: "/lab/brand-color-game/flags/france.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/france-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/fr.svg`,
  },
  {
    id: "germany",
    name: "Germany",
    targetHex: "#DD0000",
    answerName: "Germany flag red",
    flagSrc: "/lab/brand-color-game/flags/germany.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/germany-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/de.svg`,
  },
  {
    id: "italy",
    name: "Italy",
    targetHex: "#008C45",
    answerName: "Italy flag green",
    flagSrc: "/lab/brand-color-game/flags/italy.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/italy-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/it.svg`,
  },
  {
    id: "japan",
    name: "Japan",
    targetHex: "#BC002D",
    answerName: "Japan flag red",
    flagSrc: "/lab/brand-color-game/flags/japan.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/japan-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/jp.svg`,
  },
  {
    id: "canada",
    name: "Canada",
    targetHex: "#D52B1E",
    answerName: "Canada flag red",
    flagSrc: "/lab/brand-color-game/flags/canada.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/canada-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/ca.svg`,
  },
  {
    id: "united-kingdom",
    name: "United Kingdom",
    targetHex: "#012169",
    answerName: "United Kingdom flag blue",
    flagSrc: "/lab/brand-color-game/flags/united-kingdom.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/united-kingdom-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/gb.svg`,
  },
  {
    id: "brazil",
    name: "Brazil",
    targetHex: "#009B3A",
    answerName: "Brazil flag green",
    flagSrc: "/lab/brand-color-game/flags/brazil.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/brazil-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/br.svg`,
  },
  {
    id: "mexico",
    name: "Mexico",
    targetHex: "#006847",
    answerName: "Mexico flag green",
    flagSrc: "/lab/brand-color-game/flags/mexico.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/mexico-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/mx.svg`,
  },
  {
    id: "india",
    name: "India",
    targetHex: "#FF9933",
    answerName: "India flag saffron",
    flagSrc: "/lab/brand-color-game/flags/india.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/india-missing.svg",
    difficulty: 1,
    source: `${FLAG_SOURCE}/in.svg`,
  },
  {
    id: "australia",
    name: "Australia",
    targetHex: "#00008B",
    answerName: "Australia flag blue",
    flagSrc: "/lab/brand-color-game/flags/australia.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/australia-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/au.svg`,
  },
  {
    id: "south-korea",
    name: "South Korea",
    targetHex: "#CD2E3A",
    answerName: "South Korea flag red",
    flagSrc: "/lab/brand-color-game/flags/south-korea.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/south-korea-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/kr.svg`,
  },
  {
    id: "spain",
    name: "Spain",
    targetHex: "#AA151B",
    answerName: "Spain flag red",
    flagSrc: "/lab/brand-color-game/flags/spain.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/spain-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/es.svg`,
  },
  {
    id: "sweden",
    name: "Sweden",
    targetHex: "#006AA7",
    answerName: "Sweden flag blue",
    flagSrc: "/lab/brand-color-game/flags/sweden.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/sweden-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/se.svg`,
  },
  {
    id: "south-africa",
    name: "South Africa",
    targetHex: "#007749",
    answerName: "South Africa flag green",
    flagSrc: "/lab/brand-color-game/flags/south-africa.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/south-africa-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/za.svg`,
  },
  {
    id: "china",
    name: "China",
    targetHex: "#EE1C25",
    answerName: "China flag red",
    flagSrc: "/lab/brand-color-game/flags/china.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/china-missing.svg",
    difficulty: 2,
    source: `${FLAG_SOURCE}/cn.svg`,
  },
  {
    id: "argentina",
    name: "Argentina",
    targetHex: "#74ACDF",
    answerName: "Argentina flag blue",
    flagSrc: "/lab/brand-color-game/flags/argentina.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/argentina-missing.svg",
    difficulty: 3,
    source: `${FLAG_SOURCE}/ar.svg`,
  },
  {
    id: "norway",
    name: "Norway",
    targetHex: "#BA0C2F",
    answerName: "Norway flag red",
    flagSrc: "/lab/brand-color-game/flags/norway.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/norway-missing.svg",
    difficulty: 3,
    source: `${FLAG_SOURCE}/no.svg`,
  },
  {
    id: "greece",
    name: "Greece",
    targetHex: "#0D5EAF",
    answerName: "Greece flag blue",
    flagSrc: "/lab/brand-color-game/flags/greece.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/greece-missing.svg",
    difficulty: 3,
    source: `${FLAG_SOURCE}/gr.svg`,
  },
  {
    id: "jamaica",
    name: "Jamaica",
    targetHex: "#007749",
    answerName: "Jamaica flag green",
    flagSrc: "/lab/brand-color-game/flags/jamaica.svg",
    missingFlagSrc: "/lab/brand-color-game/flags/jamaica-missing.svg",
    difficulty: 3,
    source: `${FLAG_SOURCE}/jm.svg`,
  },
] as const satisfies readonly BrandColorGameFlag[];
